//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Accessory
    {
        public Accessory()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int AccessoryID { get; set; }
        [Display(Name = "Name: ")]
        public string AccessoryName { get; set; }
        [Display(Name = "Photo: ")]
        public string AccessoryPhoto { get; set; }
        [Display(Name = "Type: ")]
        public string AccessoryType { get; set; }
        [Display(Name = "Color: ")]
        public string AccessoryColor { get; set; }
        [Display(Name = "Season: ")]
        public string AccessorySeason { get; set; }
        [Display(Name = "Occasion: ")]
        public string AccessoryOccasion { get; set; }
    
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
