//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bottom
    {
        public Bottom()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int BottomID { get; set; }
        [Display(Name = "Name: ")]
        public string BottomName { get; set; }
        [Display(Name = "Photo: ")]
        public string BottomPhoto { get; set; }
        [Display(Name = "Type: ")]
        public string BottomType { get; set; }
        [Display(Name = "Color: ")]
        public string BottomColor { get; set; }
        [Display(Name = "Season: ")]
        public string BottomSeason { get; set; }
        [Display(Name = "Occasion ")]
        public string BottomOccasion { get; set; }
    
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
