//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottom
    {
        public Bottom()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int BottomID { get; set; }
        public string BottomName { get; set; }
        public string BottomPhoto { get; set; }
        public string BottomType { get; set; }
        public string BottomColor { get; set; }
        public string BottomSeason { get; set; }
        public string BottomOccasion { get; set; }
    
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
